### ISSUE TITLE
Felyne Kitchen, outdoor view is incorrect

### ISSUE THREAD

**Issue by Abbanon** [Monkbreh/MHFU-Texture-Port#1]
The snow along the bottom of the cliff to the left, as seen through the window in the Felyne Kitchen, has been changed into grass.
It causes a pretty significattn cutoff line between grass and snow.
![Screenshot_2](https://github.com/Monkbreh/MHFU-Texture-Port/assets/37251822/739c05bc-d6fb-4efa-aaec-79095b559558)
![Screenshot_3](https://github.com/Monkbreh/MHFU-Texture-Port/assets/37251822/b20ecf5e-a5f3-4399-a548-a13f02ca870b)

**Comment by Monkbreh** [comment]
Noted
