### ISSUE TITLE
List of what's missing

### ISSUE THREAD

**Issue by AmyRoxwell** [Monkbreh/MHFU-Texture-Port#3]
Hello! I was interested on making my own set of textures doing what your team already did, it was just a few days ago I was informed about this project.
I read on the readme that you still have some textures missing from some monsters, could you tell what are the monsters that are missing so I could try to contribute for them? I have access to the ps2 games, psp games and frontier.
Thank you so much for this amazing project!

**Comment by Monkbreh** [comment]
Hello there !
Any contribution is welcome and to answer your question, the repo includes all the monsters except copper blango (and queen vespoid lol) . I have some incomplete drawing for him but feel free to contribute what you have. Although my priority right now is to complete the remaining equipment textures.

**Comment by AmyRoxwell** [comment]
> Hello there ! Any contribution is welcome and to answer your question, the repo includes all the monsters except copper blango (and queen vespoid lol) . I have some incomplete drawing for him but feel free to contribute what you have. Although my priority right now is to complete the remaining equipment textures.

Alrighty! thank you very much for the answer >:3.
I will try to my best to check any missing textures and see if I can get them
