### ISSUE TITLE
Gravios tail texture is messed up

### ISSUE THREAD

**Issue by AmyRoxwell** [Monkbreh/MHFU-Texture-Port#8]
Texture Hash and name are: 094239301242e767c150cb1e.png
Also, seems to be interacting with basarios textures: 094cdfd0b4cb7aae53c57bbf

Also, it flickers a lot due to z-fighting

Texture On:
![Screenshot_03012024_181555](https://github.com/Monkbreh/MHFU-Texture-Port/assets/89411895/f373dd67-7f48-44b3-a5d7-f652de397635)
Texture Off:
![Screenshot_03012024_181556](https://github.com/Monkbreh/MHFU-Texture-Port/assets/89411895/6249acb5-d083-4535-9f90-fb487993b790)
Texture On:
![Screenshot_03012024_182710](https://github.com/Monkbreh/MHFU-Texture-Port/assets/89411895/0df1d87a-ec68-4691-b155-b62a832a539b)
Texture Off:
![Screenshot_03012024_182712](https://github.com/Monkbreh/MHFU-Texture-Port/assets/89411895/83d5e7df-7fc0-4388-864d-58b2c631ea5c)
Texture On:
![Screenshot_03012024_182828](https://github.com/Monkbreh/MHFU-Texture-Port/assets/89411895/7a3a1b5e-6d80-449d-b9ef-a5d11fc97a18)
Texture Off:
![Screenshot_03012024_182858](https://github.com/Monkbreh/MHFU-Texture-Port/assets/89411895/574e9a52-2b70-4334-bed7-758d5981f626)

**Comment by Monkbreh** [comment]
Oh yeah i remember this issue, its a transparency texture issue because gravios model has less vertices than than the dos model. Anyways i fixed it a while back its included in my next repo update but i suppose i can update the texture files for this now.
